name: Convert Jupyter Notebook to README.md
on:
  push:
    paths:
      - 'README.ipynb'
jobs:
  convert_notebook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          
      - name: Convert notebook to markdown
        run: |
          jupyter nbconvert --to markdown README.ipynb --output README.md
          
      - name: Commit README.md and images
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git add README_files/ || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README.md from notebook"
          git push