name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events to the main and dev branches
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # make is manually start-able

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          miniforge-version: latest
          activate-environment: MPP
          use-mamba: true
          channels: conda-forge,defaults
          channel-priority: strict

      - name: Install environment
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --editable ".[all]"
          pip install pytest pytest-cov

      - name: Run tests
        shell: bash -l {0}
        run: |
          cd tests
          pytest --cov=../glycontact --cov-report=xml
